package com.claimguard.fraud;

public enum SignalType {
    EXACT_DUPLICATE,
    NEAR_DUPLICATE_IMAGE,
    SEMANTIC_DUPLICATE,
    REUSED_INVOICE_NUMBER,
    EDITING_SOFTWARE,
    METADATA_STRIPPED,
    MODIFIED_AFTER_CREATION,
    AI_GENERATED,
    SHARED_DEVICE,
    LINE_ITEM_MISMATCH,
    DATE_INCONSISTENCY,
    PROCEDURE_DIAGNOSIS_MISMATCH,
    AMOUNT_OUT_OF_BAND,
    MISSING_CRITICAL_FIELD
}
