package com.claimguard.audit;

public enum AuditAction {
    CLAIM_CREATED,
    CLAIM_UPDATED,
    CLAIM_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    EXTRACTION_COMPLETED,
    EXTRACTION_FAILED,
    EXTRACTION_EDITED,
    RISK_ASSESSED,
    DECISION_RECORDED,
    REVIEW_RECORDED,
    NHCX_SUBMITTED,
    AUDIT_EXPORTED
}
